### ISSUE TITLE
Feature request: Add ignored_datas like a ignored_params

### ISSUE THREAD

**Issue by gs1571** [requests-cache/aiohttp-client-cache#126]
### Feature description
Add `ignored_datas` like a `ignored_params`, to skip some part of data.

### Use case
_Is there a specific goal that this would help you accomplish, or can you provide any other context about how you would like to use this feature?_
In case of POST method some details of requests put in data field. Because some piece of data could contain information which is not suitable for cache key.

### Workarounds
_Is there an existing workaround to accomplish this?_
It looks like not

### Plan to implement
_Are you interested in submitting a PR to implement this?_
I'm not sure that I'm ready to do that.

**Comment by JWCook** [comment]
Good news, `ignored_parameters` already applies to keys in a JSON request body:
https://requests-cache.readthedocs.io/en/stable/user_guide/matching.html#selective-parameter-matching

Do you have a content type other than JSON that you want this to work with?

**Comment by gs1571** [comment]
For sure your approach is suitable for me.

In my case I'm trying caching POST request like this:
```python
async with aiohttp.ClientSession() as session:
    async with session.post(url,
                            json={
                                'from': 'some datetime object in ISO fromat',
                                'to': 'some datetime object in ISO fromat',
                                'parameter': 'some data'}
                            )
```
But `to` and `from` fields should be ignored at all.

**Comment by JWCook** [comment]
Ah, if you're using the `json` argument, I believe `ignored_params` will already work for you:
```python
from aiohttp_client_cache import CachedSession, SQLiteBackend


cache = SQLiteBackend('demo_cache', allowed_methods=['GET', 'POST'], ignored_params=['to', 'from'])

async with CachedSession(cache=cache) as session:
    r = await session.post('https://httpbin.org/post', json={'to': 1, 'from': 1, 'parameter': 1})

    # If 'to' or 'from' change, it's still a cache hit
    r = await session.post('https://httpbin.org/post', json={'to': 2, 'from': 2, 'parameter': 1})
    print(r.from_cache)

    # If 'parameter' changes, it's a cache miss (response will be cached under a different key)
    r = await session.post('https://httpbin.org/post', json={'to': 1, 'from': 1, 'parameter': 2})
    print(r.from_cache)
```

Give that a try and let me know if that does what you want.

I haven't advertised that feature yet in the docs because IMO it's not quite complete, since it only handles a request body passed via `json`. The part that's not implemented yet is a request body passed via the `data` argument that's already encoded, which is a bit trickier to handle since it might be `application/json`, `application/x-www-form-urlencoded`, `multipart/form-data`, or an `aiohttp.FormData` object.

**Comment by gs1571** [comment]
Hello!

Sorry for a long answer, I wrote simple flaks server and http client based on your lib. It looks ok.
But on other hand I still have the issue with my app. I will investigate it deeper and get back with results later.

**Comment by JWCook** [comment]
Sure. What kind of issue are you having with your app?

It may be unrelated, but generally Flask and asyncio don't mix well. You can technically [use async functions in Flask](https://flask.palletsprojects.com/en/2.1.x/async-await/), but it won't be truly async since WSGI uses a single worker and doesn't have native async support. You may get better results with either:
1. [requests](https://requests.readthedocs.io) + [requests-cache](https://github.com/requests-cache/requests-cache) + Flask, or
2. aiohttp + this library + either the [aiohttp web server](https://docs.aiohttp.org/en/stable/web.html) or an [ASGI web framework](https://asgi.readthedocs.io/en/latest/implementations.html) like FastAPI or Quart

**Comment by JWCook** [comment]
I'm closing this for now, but feel free to open another issue if you have any more problems. Or we can reopen this one, if you or someone else need this to work with something other than a request body passed via the `json` argument.
